# NGINX webservers with ingress-demo pages
# NGINX for Azure, Mar 2024
# Chris Akker, Shouvik Dutta, Adam Currier
#
services:
  web1:
      hostname: docker-web1
      container_name: docker-web1
      image: nginxinc/ingress-demo            # Image from Docker Hub
      restart: always
      ports:
        - "81:80"                                # Open for HTTP
        - "4431:443"                             # Open for HTTPS
  web2:
      hostname: docker-web2
      container_name: docker-web2
      image: nginxinc/ingress-demo
      restart: always
      ports:
        - "82:80"
        - "4432:443"
  web3:
      hostname: docker-web3
      container_name: docker-web3
      image: nginxinc/ingress-demo
      restart: always
      ports:
        - "83:80"
        - "4433:443"