apiVersion: k8s.nginx.org/v1
kind: Policy
metadata:
  name: oidc-policy
spec:
  oidc:
    clientID: e30e003e-a3b9-4df1-bb94-3890ca75ddb2
    clientSecret: oidc-secret # Name of the kubernetes secret that you created 
    authEndpoint: https://login.microsoftonline.com/ab998f66-905c-4e29-9c18-d4f34756fe33/oauth2/v2.0/authorize
    tokenEndpoint: https://login.microsoftonline.com/ab998f66-905c-4e29-9c18-d4f34756fe33/oauth2/v2.0/token
    jwksURI: https://login.microsoftonline.com/ab998f66-905c-4e29-9c18-d4f34756fe33/discovery/v2.0/keys
    scope: openid+profile+email
    accessTokenEnable: true