apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress
  namespace: nginx-ingress
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 32080
    protocol: TCP
    name: http
  - port: 443
    nodePort: 32443
    protocol: TCP
    name: https
  - port: 6379
    nodePort: 32379
    protocol: TCP
    name: redis-leader
  - port: 6380
    nodePort: 32380
    protocol: TCP
    name: redis-follower
  - port: 9000
    nodePort: 32090
    protocol: TCP
    name: dashboard    
  selector:
    app: nginx-ingress
    