apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: prometheus-vs 
  namespace: monitoring
spec:
  host: acurrier-azure-monitor-workspace-f4eugyefg6buc2a6.MY_LOCATION.prometheus.monitor.azure.com
  upstreams:
  - name: prometheus 
    service: nginx-prometheus-server
    port: 443 
  routes:
  - path: /
    action:
      pass: prometheus
      
