apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress
  namespace: nginx-ingress
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 32080
    protocol: TCP
    name: http
  - port: 443
    nodePort: 32443
    protocol: TCP
    name: https
  selector:
    app: nginx-ingress
    