{
 "title": "Nginx4AzureDashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "HTTP Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "NGINX Requests and Response Statistics",
      "dimensionFilters": [
       {
        "dimension": "server_zone",
        "filters": [],
        "operator": "eq"
       },
       {
        "dimension": "",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "plus.http.request.count",
      "metricNamespace": "nginx.nginxplus/nginxdeployments",
      "region": "westus2",
      "resources": [
       {
        "metricNamespace": "NGINX.NGINXPLUS/nginxDeployments",
        "region": "westus2",
        "resourceGroup": "cakker",
        "resourceName": "nginx1",
        "subscription": "7a0bb4ab-c5a7-46b3-b4ad-c10376166020"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "7a0bb4ab-c5a7-46b3-b4ad-c10376166020"
    }
   ]
  },
  {
   "title": "HTTP Metrics",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "NGINX Requests and Response Statistics",
      "dimensionFilters": [],
      "metricName": "plus.http.status.2xx",
      "metricNamespace": "nginx.nginxplus/nginxdeployments",
      "region": "westus2",
      "resources": [
       {
        "metricNamespace": "NGINX.NGINXPLUS/nginxDeployments",
        "region": "westus2",
        "resourceGroup": "cakker",
        "resourceName": "nginx1",
        "subscription": "7a0bb4ab-c5a7-46b3-b4ad-c10376166020"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "7a0bb4ab-c5a7-46b3-b4ad-c10376166020"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "NGINX Requests and Response Statistics",
      "dimensionFilters": [],
      "metricName": "plus.http.status.3xx",
      "metricNamespace": "nginx.nginxplus/nginxdeployments",
      "region": "westus2",
      "resources": [
       {
        "metricNamespace": "NGINX.NGINXPLUS/nginxDeployments",
        "region": "westus2",
        "resourceGroup": "cakker",
        "resourceName": "nginx1",
        "subscription": "7a0bb4ab-c5a7-46b3-b4ad-c10376166020"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "7a0bb4ab-c5a7-46b3-b4ad-c10376166020"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "NGINX Requests and Response Statistics",
      "dimensionFilters": [],
      "metricName": "plus.http.status.4xx",
      "metricNamespace": "nginx.nginxplus/nginxdeployments",
      "region": "westus2",
      "resources": [
       {
        "metricNamespace": "NGINX.NGINXPLUS/nginxDeployments",
        "region": "westus2",
        "resourceGroup": "cakker",
        "resourceName": "nginx1",
        "subscription": "7a0bb4ab-c5a7-46b3-b4ad-c10376166020"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "7a0bb4ab-c5a7-46b3-b4ad-c10376166020"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "NGINX Requests and Response Statistics",
      "dimensionFilters": [],
      "metricName": "plus.http.status.5xx",
      "metricNamespace": "nginx.nginxplus/nginxdeployments",
      "region": "westus2",
      "resources": [
       {
        "metricNamespace": "NGINX.NGINXPLUS/nginxDeployments",
        "region": "westus2",
        "resourceGroup": "cakker",
        "resourceName": "nginx1",
        "subscription": "7a0bb4ab-c5a7-46b3-b4ad-c10376166020"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "7a0bb4ab-c5a7-46b3-b4ad-c10376166020"
    }
   ]
  },
  {
   "title": "Cache Hit Ratio",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "NGINX Cache Statistics",
      "dimensionFilters": [
       { "dimension": "cache_zone", "filters": [ "image_cache" ], "operator": "eq" }
      ],
      "metricName": "plus.cache.hit.ratio",
      "metricNamespace": "nginx.nginxplus/nginxdeployments",
      "region": "westus2",
      "resources": [
       {
        "metricNamespace": "NGINX.NGINXPLUS/nginxDeployments",
        "region": "westus2",
        "resourceGroup": "cakker",
        "resourceName": "nginx1",
        "subscription": "7a0bb4ab-c5a7-46b3-b4ad-c10376166020"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "7a0bb4ab-c5a7-46b3-b4ad-c10376166020"
    }
   ]
  },
  {
   "title": "SSL Metrics",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Count",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "NGINX SSL Statistics",
      "dimensionFilters": [
       {
        "dimension": "server_zone",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "plus.http.ssl.handshakes",
      "metricNamespace": "nginx.nginxplus/nginxdeployments",
      "region": "westus2",
      "resources": [
       {
        "metricNamespace": "NGINX.NGINXPLUS/nginxDeployments",
        "region": "westus2",
        "resourceGroup": "cakker",
        "resourceName": "nginx1",
        "subscription": "7a0bb4ab-c5a7-46b3-b4ad-c10376166020"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "7a0bb4ab-c5a7-46b3-b4ad-c10376166020"
    },
    {
     "azureMonitor": {
      "aggregation": "Count",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "NGINX SSL Statistics",
      "dimensionFilters": [
       {
        "dimension": "server_zone",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "plus.http.ssl.session.reuses",
      "metricNamespace": "nginx.nginxplus/nginxdeployments",
      "region": "westus2",
      "resources": [
       {
        "metricNamespace": "NGINX.NGINXPLUS/nginxDeployments",
        "region": "westus2",
        "resourceGroup": "cakker",
        "resourceName": "nginx1",
        "subscription": "7a0bb4ab-c5a7-46b3-b4ad-c10376166020"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "7a0bb4ab-c5a7-46b3-b4ad-c10376166020"
    },
    {
     "azureMonitor": {
      "aggregation": "Count",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "NGINX SSL Statistics",
      "dimensionFilters": [
       {
        "dimension": "server_zone",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "plus.http.ssl.handshakes.failed",
      "metricNamespace": "nginx.nginxplus/nginxdeployments",
      "region": "westus2",
      "resources": [
       {
        "metricNamespace": "NGINX.NGINXPLUS/nginxDeployments",
        "region": "westus2",
        "resourceGroup": "cakker",
        "resourceName": "nginx1",
        "subscription": "7a0bb4ab-c5a7-46b3-b4ad-c10376166020"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "7a0bb4ab-c5a7-46b3-b4ad-c10376166020"
    }
   ]
  },
  {
   "title": "Upstream Response Time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "NGINX Upstream Statistics",
      "dimensionFilters": [
       {
        "dimension": "upstream",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "plus.http.upstream.peers.response.time",
      "metricNamespace": "nginx.nginxplus/nginxdeployments",
      "region": "westus2",
      "resources": [
       {
        "metricNamespace": "NGINX.NGINXPLUS/nginxDeployments",
        "region": "westus2",
        "resourceGroup": "cakker",
        "resourceName": "nginx1",
        "subscription": "7a0bb4ab-c5a7-46b3-b4ad-c10376166020"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "7a0bb4ab-c5a7-46b3-b4ad-c10376166020"
    }
   ]
  },
  {
   "title": "Health Checks",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Count",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "NGINX Upstream Statistics",
      "dimensionFilters": [
       {
        "dimension": "upstream",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "plus.http.upstream.peers.health_checks.checks",
      "metricNamespace": "nginx.nginxplus/nginxdeployments",
      "region": "westus2",
      "resources": [
       {
        "metricNamespace": "NGINX.NGINXPLUS/nginxDeployments",
        "region": "westus2",
        "resourceGroup": "cakker",
        "resourceName": "nginx1",
        "subscription": "7a0bb4ab-c5a7-46b3-b4ad-c10376166020"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "7a0bb4ab-c5a7-46b3-b4ad-c10376166020"
    },
    {
     "azureMonitor": {
      "aggregation": "Count",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "NGINX Upstream Statistics",
      "dimensionFilters": [
       {
        "dimension": "upstream",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "plus.http.upstream.peers.health_checks.unhealthy",
      "metricNamespace": "nginx.nginxplus/nginxdeployments",
      "region": "westus2",
      "resources": [
       {
        "metricNamespace": "NGINX.NGINXPLUS/nginxDeployments",
        "region": "westus2",
        "resourceGroup": "cakker",
        "resourceName": "nginx1",
        "subscription": "7a0bb4ab-c5a7-46b3-b4ad-c10376166020"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "7a0bb4ab-c5a7-46b3-b4ad-c10376166020"
    }
   ]
  }
 ]
}