{
 "title": "Nginx 4 Azure Workshop",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "MY_LOCATION", "query": "eastus" },
   { "name": "MY_RESOURCEGROUP", "query": "a.currier-workshop" },
   { "name": "MY_RESOURCENAME", "query": "nginx4a" },
   { "name": "AKSCluster1", "label": "AKS Cluster 1", "query": "n4a-aks1" },
   { "name": "AKSCluster2", "label": "AKS Cluster 2", "query": "n4a-aks2" },
   { "name": "windowsvm", "label": "Windows VM", "query": "windowsvm" },
   { "name": "ubuntuvm", "label": "Ubuntu VM", "query": "ubuntuvm" }
  ]
 },
 "panels": [
  { "title": "NGINXaaS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "NCU Stats",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Count",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "nginxaas statistics",
      "dimensionFilters": [],
      "metricName": "ncu.provisioned",
      "metricNamespace": "nginx.nginxplus/nginxdeployments",
      "region": "$MY_LOCATION",
      "resources": [
       {
        "metricNamespace": "Nginx.NginxPlus/nginxDeployments",
        "region": "$MY_LOCATION",
        "resourceGroup": "$MY_RESOURCEGROUP",
        "resourceName": "$MY_RESOURCENAME"
       }
      ],
      "timeGrain": "auto"
     }
    },
    {
     "azureMonitor": {
      "aggregation": "Count",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "nginxaas statistics",
      "dimensionFilters": [],
      "metricName": "ncu.requested",
      "metricNamespace": "nginx.nginxplus/nginxdeployments",
      "region": "$MY_LOCATION",
      "resources": [
       {
        "metricNamespace": "Nginx.NginxPlus/nginxDeployments",
        "region": "$MY_LOCATION",
        "resourceGroup": "$MY_RESOURCEGROUP",
        "resourceName": "$MY_RESOURCENAME"
       }
      ],
      "timeGrain": "auto"
     }
    },
    {
     "azureMonitor": {
      "aggregation": "Count",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "NGINXaaS Statistics",
      "dimensionFilters": [],
      "metricName": "ncu.consumed",
      "metricNamespace": "nginx.nginxplus/nginxdeployments",
      "region": "$MY_LOCATION",
      "resources": [
       {
        "metricNamespace": "Nginx.NginxPlus/nginxDeployments",
        "region": "$MY_LOCATION",
        "resourceGroup": "$MY_RESOURCEGROUP",
        "resourceName": "$MY_RESOURCENAME"
       }
      ],
      "timeGrain": "auto"
     }
    }
   ]
  },
  {
   "title": "NGINX connections statistics",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Count",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "NGINX Connections Statistics",
      "dimensionFilters": [],
      "metricName": "nginx.conn.accepted",
      "metricNamespace": "nginx.nginxplus/nginxdeployments",
      "region": "$MY_LOCATION",
      "resources": [
       {
        "metricNamespace": "Nginx.NginxPlus/nginxDeployments",
        "region": "$MY_LOCATION",
        "resourceGroup": "$MY_RESOURCEGROUP",
        "resourceName": "$MY_RESOURCENAME"
       }
      ],
      "timeGrain": "auto"
     }
    },
    {
     "azureMonitor": {
      "aggregation": "Count",
      "alias": "",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "NGINX Connections Statistics",
      "dimensionFilters": [],
      "metricName": "nginx.conn.dropped",
      "metricNamespace": "nginx.nginxplus/nginxdeployments",
      "region": "$MY_LOCATION",
      "resources": [
       {
        "metricNamespace": "Nginx.NginxPlus/nginxDeployments",
        "region": "$MY_LOCATION",
        "resourceGroup": "$MY_RESOURCEGROUP",
        "resourceName": "$MY_RESOURCENAME"
       }
      ],
      "timeGrain": "auto",
      "top": ""
     }
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "NGINX Connections Statistics",
      "dimensionFilters": [],
      "metricName": "nginx.conn.active",
      "metricNamespace": "nginx.nginxplus/nginxdeployments",
      "region": "$MY_LOCATION",
      "resources": [
       {
        "metricNamespace": "Nginx.NginxPlus/nginxDeployments",
        "region": "$MY_LOCATION",
        "resourceGroup": "$MY_RESOURCEGROUP",
        "resourceName": "$MY_RESOURCENAME"
       }
      ],
      "timeGrain": "auto"
     }
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "NGINX Connections Statistics",
      "dimensionFilters": [],
      "metricName": "nginx.conn.idle",
      "metricNamespace": "nginx.nginxplus/nginxdeployments",
      "region": "$MY_LOCATION",
      "resources": [
       {
        "metricNamespace": "Nginx.NginxPlus/nginxDeployments",
        "region": "$MY_LOCATION",
        "resourceGroup": "$MY_RESOURCEGROUP",
        "resourceName": "$MY_RESOURCENAME"
       }
      ],
      "timeGrain": "auto"
     }
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "NGINX Connections Statistics",
      "dimensionFilters": [],
      "metricName": "nginx.conn.current",
      "metricNamespace": "nginx.nginxplus/nginxdeployments",
      "region": "$MY_LOCATION",
      "resources": [
       {
        "metricNamespace": "Nginx.NginxPlus/nginxDeployments",
        "region": "$MY_LOCATION",
        "resourceGroup": "$MY_RESOURCEGROUP",
        "resourceName": "$MY_RESOURCENAME"
       }
      ],
      "timeGrain": "auto"
     }
    }
   ]
  },
  {
   "title": "NGINX worker statistics",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Count",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "NGINX Worker Statistics",
      "dimensionFilters": [],
      "metricName": "plus.worker.conn.accepted",
      "metricNamespace": "nginx.nginxplus/nginxdeployments",
      "region": "$MY_LOCATION",
      "resources": [
       {
        "metricNamespace": "Nginx.NginxPlus/nginxDeployments",
        "region": "$MY_LOCATION",
        "resourceGroup": "$MY_RESOURCEGROUP",
        "resourceName": "$MY_RESOURCENAME"
       }
      ],
      "timeGrain": "auto"
     }
    },
    {
     "azureMonitor": {
      "aggregation": "Count",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "NGINX Worker Statistics",
      "dimensionFilters": [],
      "metricName": "plus.worker.conn.dropped",
      "metricNamespace": "nginx.nginxplus/nginxdeployments",
      "region": "$MY_LOCATION",
      "resources": [
       {
        "metricNamespace": "Nginx.NginxPlus/nginxDeployments",
        "region": "$MY_LOCATION",
        "resourceGroup": "$MY_RESOURCEGROUP",
        "resourceName": "$MY_RESOURCENAME"
       }
      ],
      "timeGrain": "auto"
     }
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "NGINX Worker Statistics",
      "dimensionFilters": [],
      "metricName": "plus.worker.conn.active",
      "metricNamespace": "nginx.nginxplus/nginxdeployments",
      "region": "$MY_LOCATION",
      "resources": [
       {
        "metricNamespace": "Nginx.NginxPlus/nginxDeployments",
        "region": "$MY_LOCATION",
        "resourceGroup": "$MY_RESOURCEGROUP",
        "resourceName": "$MY_RESOURCENAME"
       }
      ],
      "timeGrain": "auto"
     }
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "NGINX Worker Statistics",
      "dimensionFilters": [],
      "metricName": "plus.worker.conn.idle",
      "metricNamespace": "nginx.nginxplus/nginxdeployments",
      "region": "$MY_LOCATION",
      "resources": [
       {
        "metricNamespace": "Nginx.NginxPlus/nginxDeployments",
        "region": "$MY_LOCATION",
        "resourceGroup": "$MY_RESOURCEGROUP",
        "resourceName": "$MY_RESOURCENAME"
       }
      ],
      "timeGrain": "auto"
     }
    },
    {
     "azureMonitor": {
      "aggregation": "Count",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "NGINX Worker Statistics",
      "dimensionFilters": [],
      "metricName": "plus.worker.http.request.total",
      "metricNamespace": "nginx.nginxplus/nginxdeployments",
      "region": "$MY_LOCATION",
      "resources": [
       {
        "metricNamespace": "Nginx.NginxPlus/nginxDeployments",
        "region": "$MY_LOCATION",
        "resourceGroup": "$MY_RESOURCEGROUP",
        "resourceName": "$MY_RESOURCENAME"
       }
      ],
      "timeGrain": "auto"
     }
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "NGINX Worker Statistics",
      "dimensionFilters": [],
      "metricName": "plus.worker.http.request.current",
      "metricNamespace": "nginx.nginxplus/nginxdeployments",
      "region": "$MY_LOCATION",
      "resources": [
       {
        "metricNamespace": "Nginx.NginxPlus/nginxDeployments",
        "region": "$MY_LOCATION",
        "resourceGroup": "$MY_RESOURCEGROUP",
        "resourceName": "$MY_RESOURCENAME"
       }
      ],
      "timeGrain": "auto"
     }
    }
   ]
  },
  {
   "title": "Upstream Response Time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "NGINX Upstream Statistics",
      "dimensionFilters": [
       {
        "dimension": "upstream",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "plus.http.upstream.peers.response.time",
      "metricNamespace": "nginx.nginxplus/nginxdeployments",
      "region": "$MY_LOCATION",
      "resources": [
       {
        "metricNamespace": "NGINX.NGINXPLUS/nginxDeployments",
        "region": "$MY_LOCATION",
        "resourceGroup": "$MY_RESOURCEGROUP",
        "resourceName": "$MY_RESOURCENAME"
       }
      ],
      "timeGrain": "auto"
     }
    }
   ]
  },
  {
   "title": "HTTP Metrics",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "NGINX Requests and Response Statistics",
      "dimensionFilters": [],
      "metricName": "plus.http.status.2xx",
      "metricNamespace": "nginx.nginxplus/nginxdeployments",
      "region": "$MY_LOCATION",
      "resources": [
       {
        "metricNamespace": "NGINX.NGINXPLUS/nginxDeployments",
        "region": "$MY_LOCATION",
        "resourceGroup": "$MY_RESOURCEGROUP",
        "resourceName": "$MY_RESOURCENAME"
       }
      ],
      "timeGrain": "auto"
     }
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "NGINX Requests and Response Statistics",
      "dimensionFilters": [],
      "metricName": "plus.http.status.3xx",
      "metricNamespace": "nginx.nginxplus/nginxdeployments",
      "region": "$MY_LOCATION",
      "resources": [
       {
        "metricNamespace": "NGINX.NGINXPLUS/nginxDeployments",
        "region": "$MY_LOCATION",
        "resourceGroup": "$MY_RESOURCEGROUP",
        "resourceName": "$MY_RESOURCENAME"
       }
      ],
      "timeGrain": "auto"
     }
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "NGINX Requests and Response Statistics",
      "dimensionFilters": [],
      "metricName": "plus.http.status.4xx",
      "metricNamespace": "nginx.nginxplus/nginxdeployments",
      "region": "$MY_LOCATION",
      "resources": [
       {
        "metricNamespace": "NGINX.NGINXPLUS/nginxDeployments",
        "region": "$MY_LOCATION",
        "resourceGroup": "$MY_RESOURCEGROUP",
        "resourceName": "$MY_RESOURCENAME"
       }
      ],
      "timeGrain": "auto"
     }
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "NGINX Requests and Response Statistics",
      "dimensionFilters": [],
      "metricName": "plus.http.status.5xx",
      "metricNamespace": "nginx.nginxplus/nginxdeployments",
      "region": "$MY_LOCATION",
      "resources": [
       {
        "metricNamespace": "NGINX.NGINXPLUS/nginxDeployments",
        "region": "$MY_LOCATION",
        "resourceGroup": "$MY_RESOURCEGROUP",
        "resourceName": "$MY_RESOURCENAME"
       }
      ],
      "timeGrain": "auto"
     }
    }
   ]
  },
  {
   "title": "NGINX system statistics",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "nginx system statistics",
      "dimensionFilters": [],
      "metricName": "system.cpu",
      "metricNamespace": "nginx.nginxplus/nginxdeployments",
      "region": "$MY_LOCATION",
      "resources": [
       {
        "metricNamespace": "Nginx.NginxPlus/nginxDeployments",
        "region": "$MY_LOCATION",
        "resourceGroup": "$MY_RESOURCEGROUP",
        "resourceName": "$MY_RESOURCENAME"
       }
      ],
      "timeGrain": "auto"
     }
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "nginx system statistics",
      "dimensionFilters": [],
      "metricName": "system.interface.bytes_rcvd",
      "metricNamespace": "nginx.nginxplus/nginxdeployments",
      "region": "$MY_LOCATION",
      "resources": [
       {
        "metricNamespace": "Nginx.NginxPlus/nginxDeployments",
        "region": "$MY_LOCATION",
        "resourceGroup": "$MY_RESOURCEGROUP",
        "resourceName": "$MY_RESOURCENAME"
       }
      ],
      "timeGrain": "auto"
     }
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "nginx system statistics",
      "dimensionFilters": [],
      "metricName": "system.interface.bytes_sent",
      "metricNamespace": "nginx.nginxplus/nginxdeployments",
      "region": "$MY_LOCATION",
      "resources": [
       {
        "metricNamespace": "Nginx.NginxPlus/nginxDeployments",
        "region": "$MY_LOCATION",
        "resourceGroup": "$MY_RESOURCEGROUP",
        "resourceName": "$MY_RESOURCENAME"
       }
      ],
      "timeGrain": "auto"
     }
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "nginx system statistics",
      "dimensionFilters": [],
      "metricName": "system.interface.packets_rcvd",
      "metricNamespace": "nginx.nginxplus/nginxdeployments",
      "region": "$MY_LOCATION",
      "resources": [
       {
        "metricNamespace": "Nginx.NginxPlus/nginxDeployments",
        "region": "$MY_LOCATION",
        "resourceGroup": "$MY_RESOURCEGROUP",
        "resourceName": "$MY_RESOURCENAME"
       }
      ],
      "timeGrain": "auto"
     }
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "nginx system statistics",
      "dimensionFilters": [],
      "metricName": "system.interface.packets_sent",
      "metricNamespace": "nginx.nginxplus/nginxdeployments",
      "region": "$MY_LOCATION",
      "resources": [
       {
        "metricNamespace": "Nginx.NginxPlus/nginxDeployments",
        "region": "$MY_LOCATION",
        "resourceGroup": "$MY_RESOURCEGROUP",
        "resourceName": "$MY_RESOURCENAME"
       }
      ],
      "timeGrain": "auto"
     }
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "nginx system statistics",
      "dimensionFilters": [],
      "metricName": "system.interface.total_bytes",
      "metricNamespace": "nginx.nginxplus/nginxdeployments",
      "region": "$MY_LOCATION",
      "resources": [
       {
        "metricNamespace": "Nginx.NginxPlus/nginxDeployments",
        "region": "$MY_LOCATION",
        "resourceGroup": "$MY_RESOURCEGROUP",
        "resourceName": "$MY_RESOURCENAME"
       }
      ],
      "timeGrain": "auto"
     }
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "nginx system statistics",
      "dimensionFilters": [],
      "metricName": "system.interface.egress_throughput",
      "metricNamespace": "nginx.nginxplus/nginxdeployments",
      "region": "$MY_LOCATION",
      "resources": [
       {
        "metricNamespace": "Nginx.NginxPlus/nginxDeployments",
        "region": "$MY_LOCATION",
        "resourceGroup": "$MY_RESOURCEGROUP",
        "resourceName": "$MY_RESOURCENAME"
       }
      ],
      "timeGrain": "auto"
     }
    }
   ]
  },
  {
   "title": "SSL Metrics",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Count",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "NGINX SSL Statistics",
      "dimensionFilters": [
       {
        "dimension": "server_zone",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "plus.http.ssl.handshakes",
      "metricNamespace": "nginx.nginxplus/nginxdeployments",
      "region": "$MY_LOCATION",
      "resources": [
       {
        "metricNamespace": "NGINX.NGINXPLUS/nginxDeployments",
        "region": "$MY_LOCATION",
        "resourceGroup": "$MY_RESOURCEGROUP",
        "resourceName": "$MY_RESOURCENAME"
       }
      ],
      "timeGrain": "auto"
     }
    },
    {
     "azureMonitor": {
      "aggregation": "Count",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "NGINX SSL Statistics",
      "dimensionFilters": [
       {
        "dimension": "server_zone",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "plus.http.ssl.session.reuses",
      "metricNamespace": "nginx.nginxplus/nginxdeployments",
      "region": "$MY_LOCATION",
      "resources": [
       {
        "metricNamespace": "NGINX.NGINXPLUS/nginxDeployments",
        "region": "$MY_LOCATION",
        "resourceGroup": "$MY_RESOURCEGROUP",
        "resourceName": "$MY_RESOURCENAME"
       }
      ],
      "timeGrain": "auto"
     }
    },
    {
     "azureMonitor": {
      "aggregation": "Count",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "NGINX SSL Statistics",
      "dimensionFilters": [
       {
        "dimension": "server_zone",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "plus.http.ssl.handshakes.failed",
      "metricNamespace": "nginx.nginxplus/nginxdeployments",
      "region": "$MY_LOCATION",
      "resources": [
       {
        "metricNamespace": "NGINX.NGINXPLUS/nginxDeployments",
        "region": "$MY_LOCATION",
        "resourceGroup": "$MY_RESOURCEGROUP",
        "resourceName": "$MY_RESOURCENAME"
       }
      ],
      "timeGrain": "auto"
     }
    }
   ]
  },
  {
   "title": "Cache Hit Ratio",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "NGINX Cache Statistics",
      "dimensionFilters": [
       { "dimension": "cache_zone", "filters": [ "image_cache" ], "operator": "eq" }
      ],
      "metricName": "plus.cache.hit.ratio",
      "metricNamespace": "nginx.nginxplus/nginxdeployments",
      "region": "$MY_LOCATION",
      "resources": [
       {
        "metricNamespace": "NGINX.NGINXPLUS/nginxDeployments",
        "region": "$MY_LOCATION",
        "resourceGroup": "$MY_RESOURCEGROUP",
        "resourceName": "$MY_RESOURCENAME"
       }
      ],
      "timeGrain": "auto"
     }
    }
   ]
  },
  {
   "title": "Health Checks",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 28 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Count",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "NGINX Upstream Statistics",
      "dimensionFilters": [
       {
        "dimension": "upstream",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "plus.http.upstream.peers.health_checks.checks",
      "metricNamespace": "nginx.nginxplus/nginxdeployments",
      "region": "$MY_LOCATION",
      "resources": [
       {
        "metricNamespace": "NGINX.NGINXPLUS/nginxDeployments",
        "region": "$MY_LOCATION",
        "resourceGroup": "$MY_RESOURCEGROUP",
        "resourceName": "$MY_RESOURCENAME"
       }
      ],
      "timeGrain": "auto"
     }
    },
    {
     "azureMonitor": {
      "aggregation": "Count",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "customNamespace": "NGINX Upstream Statistics",
      "dimensionFilters": [
       {
        "dimension": "upstream",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "plus.http.upstream.peers.health_checks.unhealthy",
      "metricNamespace": "nginx.nginxplus/nginxdeployments",
      "region": "$MY_LOCATION",
      "resources": [
       {
        "metricNamespace": "NGINX.NGINXPLUS/nginxDeployments",
        "region": "$MY_LOCATION",
        "resourceGroup": "$MY_RESOURCEGROUP",
        "resourceName": "$MY_RESOURCENAME"
       }
      ],
      "timeGrain": "auto"
     }
    }
   ]
  },
  {
   "title": "K8s Clusters",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "panels": [
    {
     "title": "AKS1 Inflight Requests",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "azureMonitor": {
        "aggregation": "Average",
        "allowedTimeGrainsMs": [
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000
        ],
        "dimensionFilters": [],
        "metricName": "apiserver_current_inflight_requests",
        "metricNamespace": "microsoft.containerservice/managedclusters",
        "region": "$MY_LOCATION",
        "resources": [
         {
          "metricNamespace": "Microsoft.ContainerService/managedClusters",
          "region": "$MY_LOCATION",
          "resourceGroup": "$MY_RESOURCEGROUP",
          "resourceName": "$AKSCluster1"
         }
        ],
        "timeGrain": "auto"
       }
      }
     ]
    },
    {
     "title": "AKS2 Inflight Requests",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "azureMonitor": {
        "aggregation": "Average",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000
        ],
        "dimensionFilters": [],
        "metricName": "apiserver_current_inflight_requests",
        "metricNamespace": "microsoft.containerservice/managedclusters",
        "region": "$MY_LOCATION",
        "resources": [
         {
          "metricNamespace": "Microsoft.ContainerService/managedClusters",
          "region": "$MY_LOCATION",
          "resourceGroup": "$MY_RESOURCEGROUP",
          "resourceName": "$AKSCluster2"
         }
        ],
        "timeGrain": "auto"
       }
      }
     ]
    },
    {
     "title": "AKS 1 Network Stats",
     "type": "stat",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "azureMonitor": {
        "aggregation": "Average",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000
        ],
        "dimensionFilters": [],
        "metricName": "node_network_in_bytes",
        "metricNamespace": "microsoft.containerservice/managedclusters",
        "region": "$MY_LOCATION",
        "resources": [
         {
          "metricNamespace": "Microsoft.ContainerService/managedClusters",
          "region": "$MY_LOCATION",
          "resourceGroup": "$MY_RESOURCEGROUP",
          "resourceName": "$AKSCluster1"
         }
        ],
        "timeGrain": "auto"
       }
      },
      {
       "azureMonitor": {
        "aggregation": "Average",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000
        ],
        "dimensionFilters": [],
        "metricName": "node_network_out_bytes",
        "metricNamespace": "microsoft.containerservice/managedclusters",
        "region": "$MY_LOCATION",
        "resources": [
         {
          "metricNamespace": "Microsoft.ContainerService/managedClusters",
          "region": "$MY_LOCATION",
          "resourceGroup": "$MY_RESOURCEGROUP",
          "resourceName": "$AKSCluster1"
         }
        ],
        "timeGrain": "auto"
       }
      }
     ]
    },
    {
     "title": "AKS 2 Network Stats",
     "type": "stat",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "azureMonitor": {
        "aggregation": "Average",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000
        ],
        "dimensionFilters": [],
        "metricName": "node_network_in_bytes",
        "metricNamespace": "microsoft.containerservice/managedclusters",
        "region": "$MY_LOCATION",
        "resources": [
         {
          "metricNamespace": "Microsoft.ContainerService/managedClusters",
          "region": "$MY_LOCATION",
          "resourceGroup": "$MY_RESOURCEGROUP",
          "resourceName": "$AKSCluster2"
         }
        ],
        "timeGrain": "auto"
       }
      },
      {
       "azureMonitor": {
        "aggregation": "Average",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000
        ],
        "dimensionFilters": [],
        "metricName": "node_network_out_bytes",
        "metricNamespace": "microsoft.containerservice/managedclusters",
        "region": "$MY_LOCATION",
        "resources": [
         {
          "metricNamespace": "Microsoft.ContainerService/managedClusters",
          "region": "$MY_LOCATION",
          "resourceGroup": "$MY_RESOURCEGROUP",
          "resourceName": "$AKSCluster2"
         }
        ],
        "timeGrain": "auto"
       }
      }
     ]
    },
    {
     "title": "AKS1 CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
     "targets": [
      {
       "azureMonitor": {
        "aggregation": "Average",
        "allowedTimeGrainsMs": [
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000
        ],
        "dimensionFilters": [],
        "metricName": "node_cpu_usage_percentage",
        "metricNamespace": "microsoft.containerservice/managedclusters",
        "region": "$MY_LOCATION",
        "resources": [
         {
          "metricNamespace": "Microsoft.ContainerService/managedClusters",
          "region": "$MY_LOCATION",
          "resourceGroup": "$MY_RESOURCEGROUP",
          "resourceName": "$AKSCluster1"
         }
        ],
        "timeGrain": "auto"
       }
      }
     ]
    },
    {
     "title": "AKS1 CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
     "targets": [
      {
       "azureMonitor": {
        "aggregation": "Average",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000
        ],
        "dimensionFilters": [],
        "metricName": "node_cpu_usage_percentage",
        "metricNamespace": "microsoft.containerservice/managedclusters",
        "region": "$MY_LOCATION",
        "resources": [
         {
          "metricNamespace": "Microsoft.ContainerService/managedClusters",
          "region": "$MY_LOCATION",
          "resourceGroup": "$MY_RESOURCEGROUP",
          "resourceName": "$AKSCluster2"
         }
        ],
        "timeGrain": "auto"
       }
      }
     ]
    },
    {
     "title": "AKS1 Memory Working Set %",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
     "targets": [
      {
       "azureMonitor": {
        "aggregation": "Average",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000
        ],
        "dimensionFilters": [],
        "metricName": "node_memory_working_set_percentage",
        "metricNamespace": "microsoft.containerservice/managedclusters",
        "region": "$MY_LOCATION",
        "resources": [
         {
          "metricNamespace": "Microsoft.ContainerService/managedClusters",
          "region": "$MY_LOCATION",
          "resourceGroup": "$MY_RESOURCEGROUP",
          "resourceName": "$AKSCluster1"
         }
        ],
        "timeGrain": "auto"
       }
      }
     ]
    },
    {
     "title": "AKS2 Memory Working Set %",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
     "targets": [
      {
       "azureMonitor": {
        "aggregation": "Average",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000
        ],
        "dimensionFilters": [],
        "metricName": "node_memory_working_set_percentage",
        "metricNamespace": "microsoft.containerservice/managedclusters",
        "region": "$MY_LOCATION",
        "resources": [
         {
          "metricNamespace": "Microsoft.ContainerService/managedClusters",
          "region": "$MY_LOCATION",
          "resourceGroup": "$MY_RESOURCEGROUP",
          "resourceName": "$AKSCluster1"
         }
        ],
        "timeGrain": "auto"
       }
      }
     ]
    }
   ]
  },
  {
   "title": "Virtual Machines",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "panels": [
    {
     "title": "Ubuntu VM Inbound Flow",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "targets": [
      {
       "azureMonitor": {
        "aggregation": "Average",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000,
         86400000
        ],
        "dimensionFilters": [],
        "metricName": "Inbound Flows",
        "metricNamespace": "microsoft.compute/virtualmachines",
        "region": "$MY_LOCATION",
        "resources": [
         {
          "metricNamespace": "Microsoft.Compute/virtualMachines",
          "region": "$MY_LOCATION",
          "resourceGroup": "$MY_RESOURCEGROUP",
          "resourceName": "$ubuntuvm"
         }
        ],
        "timeGrain": "auto"
       }
      }
     ]
    },
    {
     "title": "Windows VM Inbound Flow",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "targets": [
      {
       "azureMonitor": {
        "aggregation": "Average",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000,
         86400000
        ],
        "dimensionFilters": [],
        "metricName": "Inbound Flows",
        "metricNamespace": "microsoft.compute/virtualmachines",
        "region": "$MY_LOCATION",
        "resources": [
         {
          "metricNamespace": "Microsoft.Compute/virtualMachines",
          "region": "$MY_LOCATION",
          "resourceGroup": "$MY_RESOURCEGROUP",
          "resourceName": "$windowsvm"
         }
        ],
        "timeGrain": "auto"
       }
      }
     ]
    },
    {
     "title": "Ubuntu System Stats",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "azureMonitor": {
        "aggregation": "Average",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000,
         86400000
        ],
        "dimensionFilters": [],
        "metricName": "Disk Read Bytes",
        "metricNamespace": "microsoft.compute/virtualmachines",
        "region": "$MY_LOCATION",
        "resources": [
         {
          "metricNamespace": "Microsoft.Compute/virtualMachines",
          "region": "$MY_LOCATION",
          "resourceGroup": "$MY_RESOURCEGROUP",
          "resourceName": "$ubuntuvm"
         }
        ],
        "timeGrain": "auto"
       }
      },
      {
       "azureMonitor": {
        "aggregation": "Average",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000,
         86400000
        ],
        "dimensionFilters": [],
        "metricName": "Disk Write Bytes",
        "metricNamespace": "microsoft.compute/virtualmachines",
        "region": "$MY_LOCATION",
        "resources": [
         {
          "metricNamespace": "Microsoft.Compute/virtualMachines",
          "region": "$MY_LOCATION",
          "resourceGroup": "$MY_RESOURCEGROUP",
          "resourceName": "$ubuntuvm"
         }
        ],
        "timeGrain": "auto"
       }
      },
      {
       "azureMonitor": {
        "aggregation": "Count",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000,
         86400000
        ],
        "dimensionFilters": [],
        "metricName": "Percentage CPU",
        "metricNamespace": "microsoft.compute/virtualmachines",
        "region": "$MY_LOCATION",
        "resources": [
         {
          "metricNamespace": "Microsoft.Compute/virtualMachines",
          "region": "$MY_LOCATION",
          "resourceGroup": "$MY_RESOURCEGROUP",
          "resourceName": "$ubuntuvm"
         }
        ],
        "timeGrain": "auto"
       }
      },
      {
       "azureMonitor": {
        "aggregation": "Total",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000,
         86400000
        ],
        "dimensionFilters": [],
        "metricName": "Available Memory Bytes",
        "metricNamespace": "microsoft.compute/virtualmachines",
        "region": "$MY_LOCATION",
        "resources": [
         {
          "metricNamespace": "Microsoft.Compute/virtualMachines",
          "region": "$MY_LOCATION",
          "resourceGroup": "$MY_RESOURCEGROUP",
          "resourceName": "$ubuntuvm"
         }
        ],
        "timeGrain": "auto"
       }
      }
     ]
    },
    {
     "title": "Windows System Stats",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "azureMonitor": {
        "aggregation": "Average",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000,
         86400000
        ],
        "dimensionFilters": [],
        "metricName": "Disk Read Bytes",
        "metricNamespace": "microsoft.compute/virtualmachines",
        "region": "$MY_LOCATION",
        "resources": [
         {
          "metricNamespace": "Microsoft.Compute/virtualMachines",
          "region": "$MY_LOCATION",
          "resourceGroup": "$MY_RESOURCEGROUP",
          "resourceName": "$windowsvm"
         }
        ],
        "timeGrain": "auto"
       }
      },
      {
       "azureMonitor": {
        "aggregation": "Total",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000,
         86400000
        ],
        "dimensionFilters": [],
        "metricName": "Disk Write Bytes",
        "metricNamespace": "microsoft.compute/virtualmachines",
        "region": "$MY_LOCATION",
        "resources": [
         {
          "metricNamespace": "Microsoft.Compute/virtualMachines",
          "region": "$MY_LOCATION",
          "resourceGroup": "$MY_RESOURCEGROUP",
          "resourceName": "$windowsvm"
         }
        ],
        "timeGrain": "auto"
       }
      },
      {
       "azureMonitor": {
        "aggregation": "Count",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000,
         86400000
        ],
        "dimensionFilters": [],
        "metricName": "Percentage CPU",
        "metricNamespace": "microsoft.compute/virtualmachines",
        "region": "$MY_LOCATION",
        "resources": [
         {
          "metricNamespace": "Microsoft.Compute/virtualMachines",
          "region": "$MY_LOCATION",
          "resourceGroup": "$MY_RESOURCEGROUP",
          "resourceName": "$windowsvm"
         }
        ],
        "timeGrain": "auto"
       }
      },
      {
       "azureMonitor": {
        "aggregation": "Total",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000,
         86400000
        ],
        "dimensionFilters": [],
        "metricName": "Available Memory Bytes",
        "metricNamespace": "microsoft.compute/virtualmachines",
        "region": "$MY_LOCATION",
        "resources": [
         {
          "metricNamespace": "Microsoft.Compute/virtualMachines",
          "region": "$MY_LOCATION",
          "resourceGroup": "$MY_RESOURCEGROUP",
          "resourceName": "$windowsvm"
         }
        ],
        "timeGrain": "auto"
       }
      }
     ]
    }
   ]
  }
 ]
}